baseurl         = "https://www.koharakazuya.net/"
theme           = "lightning"
hasCJKLanguage  = true
defaultContentLanguage = "ja"
languageCode    = "ja-jp"
title           = "Kohara's Blog"
googleAnalytics = "UA-49903910-2"
disableHugoGeneratorInject = true

[Author]
  name          = "KoharaKazuya"
  biography     = "職業はプログラマーです。趣味がプログラミングです。Web 技術が好きで、中でもフロントエンドの JS, HTML, CSS が好きです。得意なのは TypeScript, CSS, AWS, シェル芸です。"
  twitter       = "KoharaKazuya"
  github        = "KoharaKazuya"
  mail          = "reflect.results@gmail.com"

[params]
  description   = "作ったものや気付いたことを書き連ねる技術ブログ"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe    = true
